[package]
name = "proj3"
version = "0.1.0"
edition = "2021"

[dependencies]
eui48 = "1.1.0"
pcap = "2.2.0"
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_System_LibraryLoader", "Win32_System_SystemServices"] }
wintun = "0.5.0"

